package com.kratisai.controlplane.ingestion.parse;

import static org.junit.jupiter.api.Assertions.fail;

import com.kratisai.controlplane.model.NodeType;
import com.kratisai.controlplane.model.RelationType;
import java.io.File;
import java.nio.file.Path;
import org.junit.jupiter.api.Test;

class CodebaseMemoryPythonParserIntegrationTest extends BaseCodebaseMemoryParserIntegrationTest {

    private static final Path PYTHON_SAMPLE_DIR = Path.of("src/test/resources/codebase-memory/samples/python");

    @Test
    void shouldParsePythonSampleFilesWithNativeBinaryIfPresent() {
        File binaryFile = resolveBinaryPath();
        if (binaryFile == null) {
            fail("Native codebase-memory binary not found");
        }
        CodebaseMemoryParserService parserService = createParserService(binaryFile);

        // Run parser on sample directory
        runParser(parserService, PYTHON_SAMPLE_DIR);

        // Verify File nodes (deterministic: __init__.py, user_service.py, base_service.py, pyproject.toml)
        assertNodesOfType(NodeType.FILE, 4);

        // Verify Class nodes (deterministic: UserService, BaseService, project, build-system from pyproject.toml)
        assertNodesOfType(NodeType.CLASS, 4);

        // Verify Method nodes (deterministic: get_item x2, get_all_users, handle_request)
        assertNodesOfType(NodeType.METHOD, 4);

        // Verify Function nodes (deterministic: log_execution)
        assertNodesOfType(NodeType.FUNCTION, 1);

        // Verify expected edge types generated by codebase-memory for Python with exact counts
        assertEdgeOfType(RelationType.DEFINES, 24);
        assertEdgeOfType(RelationType.CALLS, 1);
        assertEdgeOfType(RelationType.DECORATES, 2);
        assertEdgeOfType(RelationType.IMPORTS, 8); // Maps from both USAGE and IMPORTS in codebase-memory
    }
}
