package com.kratisai.controlplane.ingestion.parse;

import static org.junit.jupiter.api.Assertions.fail;

import com.kratisai.controlplane.model.NodeType;
import com.kratisai.controlplane.model.RelationType;
import java.io.File;
import java.nio.file.Path;
import org.junit.jupiter.api.Test;

class CodebaseMemoryGoParserIntegrationTest extends BaseCodebaseMemoryParserIntegrationTest {

    private static final Path GO_SAMPLE_DIR = Path.of("src/test/resources/codebase-memory/samples/go");

    @Test
    void shouldParseGoSampleFilesWithNativeBinaryIfPresent() {
        File binaryFile = resolveBinaryPath();
        if (binaryFile == null) {
            fail("Native codebase-memory binary not found");
        }
        CodebaseMemoryParserService parserService = createParserService(binaryFile);

        // Run parser on sample directory
        runParser(parserService, GO_SAMPLE_DIR);

        // Verify File nodes (shape.go, circle.go, go.mod)
        assertNodesOfType(NodeType.FILE, 3);
        // Verify Module nodes (one for each file)
        assertNodesOfType(NodeType.MODULE, 3);
        // Verify Interface nodes (Shape)
        assertNodesOfType(NodeType.INTERFACE, 1);
        // Verify Class nodes (Circle struct)
        assertNodesOfType(NodeType.CLASS, 1);
        // Verify Method nodes (Shape.Area, Shape.Perimeter, Circle.Area, Circle.Perimeter)
        assertNodesOfType(NodeType.METHOD, 4);
        // Verify Function nodes (Area, Perimeter extracted alongside the interface methods)
        assertNodesOfType(NodeType.FUNCTION, 2);

        // Verify expected edge types generated by codebase-memory for Go with exact counts
        // DEFINES covers file DEFINES edges plus DEFINES_METHOD edges
        assertEdgeOfType(RelationType.DEFINES, 15);
        // IMPORTS covers USAGE edges from receiver methods to the Circle struct
        assertEdgeOfType(RelationType.IMPORTS, 2);
        // IMPLEMENTS covers the class-level IMPLEMENTS edge (Circle -> Shape) plus the
        // method-level OVERRIDE edges (Circle.Area -> Shape.Area, Circle.Perimeter -> Shape.Perimeter)
        assertEdgeOfType(RelationType.IMPLEMENTS, 3);
    }
}
