package com.kratisai.controlplane.ingestion.parse;

import static org.junit.jupiter.api.Assertions.fail;

import com.kratisai.controlplane.model.NodeType;
import com.kratisai.controlplane.model.RelationType;
import java.io.File;
import java.nio.file.Path;
import org.junit.jupiter.api.Test;

class CodebaseMemoryJavaParserIntegrationTest extends BaseCodebaseMemoryParserIntegrationTest {

    private static final Path JAVA_SAMPLE_DIR = Path.of("src/test/resources/codebase-memory/samples/java");

    @Test
    void shouldParseJavaSampleFilesWithNativeBinaryIfPresent() {
        File binaryFile = resolveBinaryPath();
        if (binaryFile == null) {
            fail("Native codebase-memory binary not found");
        }
        CodebaseMemoryParserService parserService = createParserService(binaryFile);

        // Run parser on sample directory
        runParser(parserService, JAVA_SAMPLE_DIR);

        // Verify File nodes (BaseController, UserController, UserService, UserServiceInterface)
        assertNodesOfType(NodeType.FILE, 4);
        // Verify Module nodes (one for each file)
        assertNodesOfType(NodeType.MODULE, 4);
        // Verify Class nodes (BaseController, UserController, UserService)
        assertNodesOfType(NodeType.CLASS, 3);
        // Verify INTERFACE nodes (UserServiceInterface)
        assertNodesOfType(NodeType.INTERFACE, 1);
        // Verify Method nodes (getUser x2, handleRequest, UserController constructor, getUser, listUsers)
        assertNodesOfType(NodeType.METHOD, 6);
        // Verify Field nodes (userService in UserController)
        assertNodesOfType(NodeType.FIELD, 1);
        // Verify Variable nodes (userService parameter/variable in UserController)
        assertNodesOfType(NodeType.VARIABLE, 1);

        // Verify expected edge types generated by codebase-memory for Java with exact counts
        assertEdgeOfType(RelationType.DEFINES, 23);
        assertEdgeOfType(RelationType.CALLS, 1);
        assertEdgeOfType(RelationType.IMPORTS, 6);
        assertEdgeOfType(RelationType.INHERITS, 1);
    }
}
