package com.kratisai.controlplane.ingestion.parse;

import static org.junit.jupiter.api.Assertions.fail;

import com.kratisai.controlplane.model.NodeType;
import com.kratisai.controlplane.model.RelationType;
import java.io.File;
import java.nio.file.Path;
import org.junit.jupiter.api.Test;

class CodebaseMemoryTypeScriptParserIntegrationTest extends BaseCodebaseMemoryParserIntegrationTest {

    private static final Path TYPESCRIPT_SAMPLE_DIR = Path.of("src/test/resources/codebase-memory/samples/typescript");

    @Test
    void shouldParseTypeScriptSampleFilesWithNativeBinaryIfPresent() {
        File binaryFile = resolveBinaryPath();
        if (binaryFile == null) {
            fail("Native codebase-memory binary not found");
        }
        CodebaseMemoryParserService parserService = createParserService(binaryFile);

        // Run parser on sample directory
        runParser(parserService, TYPESCRIPT_SAMPLE_DIR);

        // Verify File nodes (base.ts, UserController.ts, UserServiceInterface.ts)
        assertNodesOfType(NodeType.FILE, 3);
        // Verify Module nodes (base.ts, UserController.ts)
        assertNodesOfType(NodeType.MODULE, 3);
        // Verify Interface nodes (UserServiceInterface x2)
        assertNodesOfType(NodeType.INTERFACE, 2);
        // Verify Class nodes (BaseController x2, UserController)
        assertNodesOfType(NodeType.CLASS, 3);
        // Verify Method nodes (handleRequest x2, getUser, listUsers, processRequest)
        assertNodesOfType(NodeType.METHOD, 5);
        // Verify Function nodes (logExecution)
        assertNodesOfType(NodeType.FUNCTION, 1);

        // Verify expected edge types generated by codebase-memory for TypeScript with exact counts
        assertEdgeOfType(RelationType.DEFINES, 19);
        assertEdgeOfType(RelationType.CALLS, 1);
    }
}
